name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Clark-Sheng-Quan
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
    permissions:
      contents: write

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist"
